name: "🚀 Feature Request"
description: "새로운 기능 요청"
title: "🚀 "
labels: ["🚀 feature"]
body:
  - type: dropdown
    id: category
    attributes:
      label: "카테고리"
      description: "어떤 영역의 기능인가요?"
      options:
        - "FE"
        - "BE" 
        - "LLM"
        - "INFRA"
        - "DOCS"
        - "SHARED"
      default: 0
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "제목"
      description: "기능의 제목을 입력해주세요 (카테고리는 자동으로 추가됩니다)"
      placeholder: "예: 사용자 로그인 기능 추가"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📌 기능 설명"
      description: "구현하고자 하는 기능을 자세히 설명해주세요"
      placeholder: "어떤 기능을 원하시나요?"
    validations:
      required: true
