name: "📋 General"
description: "일반적인 이슈 (카테고리 미분류)"
title: "[GENERAL] "
labels: ["general"]
assignees: []

body:
  - type: dropdown
    id: category
    attributes:
      label: "카테고리"
      description: "가장 적합한 카테고리를 선택해주세요"
      options:
        - "🎨 Frontend"
        - "⚙️ Backend"
        - "🤖 LLM Service"
        - "🏗️ Infrastructure"
        - "📚 Documentation"
        - "🔧 DevOps"
        - "🧪 Testing"
        - "❓ Other"
      default: 7
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: "이슈 타입"
      description: "어떤 종류의 이슈인가요?"
      options:
        - "🚀 feature - 새로운 기능"
        - "🐛 bug - 버그 수정"
        - "✨ enhancement - 기능 개선"
        - "♻️ refactor - 리팩토링"
        - "📚 docs - 문서화"
        - "🧪 test - 테스트"
        - "🔧 chore - 기타 작업"
        - "❓ question - 질문"
      default: 0
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "제목"
      description: "이슈의 제목을 입력해주세요"
      placeholder: "예: 새로운 기능 구현"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 상세 설명"
      description: "이슈에 대한 자세한 설명을 작성해주세요"
      placeholder: |
        ## 설명
        무엇을 하고자 하나요?

        ## 배경
        왜 이 작업이 필요한가요?

        ## 예상 결과
        어떤 결과를 기대하나요?
    validations:
      required: true
