name: "🏗️ Infrastructure"
description: "인프라 및 DevOps 관련 이슈"
title: "[INFRA] "
labels: ["infrastructure", "🏗️ infra"]
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: "이슈 타입"
      description: "어떤 종류의 이슈인가요?"
      options:
        - "🚀 feature - 새로운 인프라 구성"
        - "🐛 bug - 배포/운영 이슈"
        - "⚡ performance - 성능 최적화"
        - "🔒 security - 보안 강화"
        - "💰 cost - 비용 최적화"
        - "🔧 maintenance - 유지보수"
        - "📊 monitoring - 모니터링 설정"
      default: 0
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "제목"
      description: "이슈의 제목을 입력해주세요"
      placeholder: "예: Redis 클러스터 구성"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 상세 설명"
      description: "이슈에 대한 자세한 설명을 작성해주세요"
      placeholder: |
        ## 설명
        어떤 인프라 작업을 수행하고자 하나요?
        
        ## 환경
        - Production/Staging/Development
        - 서비스: 
        - 관련 시스템: 
        
        ## 배경
        왜 이 작업이 필요한가요?
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ 완료 조건"
      description: "이 이슈가 완료되었다고 판단할 수 있는 조건들"
      placeholder: |
        - [ ] 인프라 구성 완료
        - [ ] 배포 스크립트 작성
        - [ ] 모니터링 설정
        - [ ] 백업/복구 방안 수립
        - [ ] 문서화 완료
        - [ ] 운영팀 인수인계
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 추가 정보"
      description: "다이어그램, 설정 파일 등"
      placeholder: "아키텍처 다이어그램, 설정 예시, 참고 자료 등"
    validations:
      required: false