name: "🤖 LLM Service"
description: "LLM 서비스 관련 이슈"
title: "[LLM] "
labels: ["llm", "🤖 ai"]
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: "이슈 타입"
      description: "어떤 종류의 이슈인가요?"
      options:
        - "🚀 feature - 새로운 LLM 기능"
        - "🐛 bug - LLM 응답 오류"
        - "⚡ performance - 응답 속도 개선"
        - "🎯 accuracy - 정확도 개선"
        - "💰 cost - 비용 최적화"
        - "🔧 integration - 외부 서비스 연동"
      default: 0
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "제목"
      description: "이슈의 제목을 입력해주세요"
      placeholder: "예: GPT-4 모델 통합"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📝 상세 설명"
      description: "이슈에 대한 자세한 설명을 작성해주세요"
      placeholder: |
        ## 설명
        어떤 LLM 기능을 구현/개선하고자 하나요?
        
        ## 모델 정보 (해당하는 경우)
        - 모델명: 
        - Provider: OpenAI/Anthropic/Google/etc
        - 용도: 
        
        ## 배경
        왜 이 작업이 필요한가요?
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ 완료 조건"
      description: "이 이슈가 완료되었다고 판단할 수 있는 조건들"
      placeholder: |
        - [ ] LLM API 연동 완료
        - [ ] 응답 품질 검증
        - [ ] 에러 핸들링 구현
        - [ ] 비용 모니터링 설정
        - [ ] 성능 테스트 완료
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 추가 정보"
      description: "API 문서, 테스트 케이스 등"
      placeholder: "관련 문서, 예상 사용량, 성능 요구사항 등"
    validations:
      required: false